"""Structured task state with transition evidence for long-horizon GUI agents."""

from __future__ import annotations

import json
from typing import Any


STRUCTURED_STATE_UPDATE_SYSTEM_PROMPT = """
You maintain compact working memory for a GUI agent after an action has run.
Use the explicitly labeled before/after screenshots to judge the transition,
then update task progress for the next action. This is a state update, not an
action-selection call.

Separate observed facts from the actor's prior intention. An action is effective
only when the screenshots or authoritative user response provide evidence that
it advanced the task. Use "uncertain" when the result cannot be verified. Never
mark work completed merely because the actor intended it, a control was tapped,
or a dialog disappeared. Preserve previously verified facts unless new evidence
contradicts them.

Keep the state concise. Record durable task facts and progress, not a replay of
the trajectory. If an action was ineffective or the screen did not change, the
next decision focus should encourage verification or a meaningfully different
approach rather than blind repetition. Return strict JSON only.

Required JSON shape:
{
  "task_summary": "brief stable description of the task and current situation",
  "completed_progress": ["only progress supported by evidence"],
  "remaining_requirements": ["work not yet verified complete"],
  "important_facts": ["task constraints, values, and authoritative user facts"],
  "current_subgoal": "one current objective, or empty string if none",
  "last_action_assessment": {
    "effectiveness": "effective|ineffective|uncertain",
    "screen_changed": true|false|null,
    "observed_result": "concrete evidence from the transition or user response"
  },
  "next_action_focus": "brief decision guidance, not coordinates or a full plan"
}
""".strip()


STRUCTURED_STATE_ACTION_NOTE = """
The verified task-state block was generated by comparing the screenshots before
and after the previous action. Use it as working memory, but treat the current
screenshot and authoritative user responses as higher-priority evidence. Do not
update or output task state in this action call. Choose exactly one next action.
""".strip()


_EFFECTIVENESS = {"effective", "ineffective", "uncertain"}


def build_structured_state_update_messages(
    *,
    goal: str,
    previous_state: dict[str, Any] | None,
    actor_reasoning: str | None,
    executed_action: dict[str, Any],
    before_image_url: str,
    after_image_url: str,
    current_turn_text: str,
) -> list[dict[str, Any]]:
    """Build the minimal, explicitly transition-labeled updater context."""
    current_turn_text = current_turn_text.replace(
        "Choose the next single action.",
        "Observe the result of the executed action.",
    )
    previous_text = (
        json.dumps(previous_state, ensure_ascii=False, indent=2)
        if previous_state is not None
        else (
            "No previous structured state exists. Initialize progress and remaining "
            "requirements from the task and the first observed transition."
        )
    )
    reasoning = (actor_reasoning or "[no explicit actor reasoning]").strip()
    action_text = json.dumps(executed_action, ensure_ascii=False, indent=2)
    user_text = (
        f"# Original Task\n{goal}\n\n"
        f"# Previous Structured State\n{previous_text}\n\n"
        f"# Previous Actor Reasoning\n{reasoning}\n\n"
        f"# Executed Action\n{action_text}\n\n"
        f"# Current Turn Information\n{current_turn_text}\n\n"
        "Compare the labeled screenshots. Update the structured state and return "
        "only the required JSON object."
    )
    return [
        {"role": "system", "content": STRUCTURED_STATE_UPDATE_SYSTEM_PROMPT},
        {
            "role": "user",
            "content": [
                {"type": "text", "text": user_text},
                {"type": "text", "text": "# Screenshot Before Executed Action"},
                {
                    "type": "image_url",
                    "image_url": {"url": before_image_url},
                },
                {"type": "text", "text": "# Screenshot After Executed Action"},
                {
                    "type": "image_url",
                    "image_url": {"url": after_image_url},
                },
            ],
        },
    ]


def parse_structured_state_response(response: str) -> dict[str, Any]:
    """Parse and validate a transition-structured state JSON response."""
    text = response.strip()
    if text.startswith("```"):
        lines = text.splitlines()
        if len(lines) >= 3 and lines[-1].strip() == "```":
            text = "\n".join(lines[1:-1]).strip()
    try:
        payload = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Structured state is not strict JSON: {exc}") from exc
    if not isinstance(payload, dict):
        raise ValueError("Structured state must be a JSON object")

    completed = _text_list(payload, "completed_progress")
    remaining = _text_list(payload, "remaining_requirements")
    completed_keys = {item.casefold() for item in completed}
    overlap = [item for item in remaining if item.casefold() in completed_keys]
    if overlap:
        raise ValueError(
            "Completed and remaining progress overlap: " + ", ".join(overlap)
        )

    assessment = payload.get("last_action_assessment")
    if not isinstance(assessment, dict):
        raise ValueError("last_action_assessment must be an object")
    effectiveness = _required_text(assessment, "effectiveness").lower()
    if effectiveness not in _EFFECTIVENESS:
        raise ValueError(f"Invalid action effectiveness: {effectiveness!r}")
    screen_changed = assessment.get("screen_changed")
    if screen_changed is not None and not isinstance(screen_changed, bool):
        raise ValueError("screen_changed must be true, false, or null")

    return {
        "task_summary": _required_text(payload, "task_summary"),
        "completed_progress": completed,
        "remaining_requirements": remaining,
        "important_facts": _text_list(payload, "important_facts"),
        "current_subgoal": _optional_text(payload.get("current_subgoal")),
        "last_action_assessment": {
            "effectiveness": effectiveness,
            "screen_changed": screen_changed,
            "observed_result": _required_text(assessment, "observed_result"),
        },
        "next_action_focus": _required_text(payload, "next_action_focus"),
    }


def inject_structured_state_for_action(
    messages: list[dict[str, Any]],
    state: dict[str, Any],
) -> list[dict[str, Any]]:
    """Inject the latest rendered structured state into only the newest user turn."""
    text = render_structured_state(state) + "\n\n" + STRUCTURED_STATE_ACTION_NOTE
    for message in reversed(messages):
        if message.get("role") != "user":
            continue
        content = message.get("content")
        if isinstance(content, str):
            message["content"] = f"{content}\n\n{text}"
            return messages
        if isinstance(content, list):
            content.append({"type": "text", "text": text})
            return messages
    raise ValueError("No user message is available for structured-state injection")


def append_structured_state_validation_feedback(
    messages: list[dict[str, Any]],
    error: str,
) -> None:
    """Guide a retry without retaining the invalid model response itself."""
    feedback = (
        "# Validation Feedback\n"
        f"The previous update was rejected: {error}\n"
        "Return a corrected strict JSON object matching the required shape."
    )
    content = messages[-1].get("content") if messages else None
    if not isinstance(content, list):
        raise ValueError("Verified-state updater has no multimodal user content")
    content.append({"type": "text", "text": feedback})


def render_structured_state(state: dict[str, Any]) -> str:
    """Render the validated state as concise actor-facing working memory."""
    assessment = state["last_action_assessment"]
    screen_changed = assessment["screen_changed"]
    changed_text = (
        "unknown" if screen_changed is None else "yes" if screen_changed else "no"
    )
    return "\n".join([
        "# Verified Task State",
        f"Summary: {state['task_summary']}",
        "",
        "Completed Progress:",
        *_bullets(state["completed_progress"]),
        "",
        "Remaining Requirements:",
        *_bullets(state["remaining_requirements"]),
        "",
        "Important Facts:",
        *_bullets(state["important_facts"]),
        "",
        f"Current Subgoal: {state['current_subgoal'] or '[none]'}",
        "",
        "Last Action Assessment:",
        f"- Effectiveness: {assessment['effectiveness']}",
        f"- Screen Changed: {changed_text}",
        f"- Observed Result: {assessment['observed_result']}",
        "",
        f"Next Decision Focus: {state['next_action_focus']}",
    ])


def latest_user_text(messages: list[dict[str, Any]]) -> str:
    """Return text from the newest persistent user turn."""
    for message in reversed(messages):
        if message.get("role") != "user":
            continue
        content = message.get("content")
        if isinstance(content, str):
            return content
        if isinstance(content, list):
            return "\n".join(
                item.get("text", "")
                for item in content
                if isinstance(item, dict) and item.get("type") == "text"
            ).strip()
        break
    return ""


def _bullets(items: list[str]) -> list[str]:
    return [f"- {item}" for item in items] or ["- [none]"]


def _text_list(payload: dict[str, Any], field: str) -> list[str]:
    value = payload.get(field)
    if not isinstance(value, list):
        raise ValueError(f"{field} must be a list")
    if len(value) > 64:
        raise ValueError(f"{field} contains more than 64 items")
    result = []
    for index, item in enumerate(value):
        if not isinstance(item, str) or not item.strip():
            raise ValueError(f"{field}[{index}] must be a non-empty string")
        result.append(item.strip())
    return result


def _required_text(payload: dict[str, Any], field: str) -> str:
    value = payload.get(field)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{field} must be a non-empty string")
    return value.strip()


def _optional_text(value: Any) -> str:
    if value is None:
        return ""
    if not isinstance(value, str):
        raise ValueError("current_subgoal must be a string")
    return value.strip()
